services:
    api:
        container_name: arthveda_api
        image: ceoshikhar/arthveda_api:beta
        logging:
            driver: loki
            options:
                loki-url: "https://${LOKI_USER}:${LOKI_PASSWORD}@loki.thor.ceoshikhar.com/loki/api/v1/push"
                loki-retries: 2
                loki-max-backoff: 800ms
                loki-timeout: 1s
                keep-file: "true"
                mode: "non-blocking"
        build:
            dockerfile: api.dockerfile
            args:
                TARGETOS: ${TARGETOS}
                TARGETARCH: ${TARGETARCH}
        environment:
            ARTHVEDA_API_ENV: production
            ARTHVEDA_API_LOG_LEVEL: ${ARTHVEDA_API_LOG_LEVEL}
            ARTHVEDA_API_LOG_FILE: ./logs/${ARTHVEDA_API_LOG_FILE}
            ARTHVEDA_DB_URL: ${ARTHVEDA_DB_URL}
            ARTHVEDA_WEB_URL: ${ARTHVEDA_WEB_URL}
            ARTHVEDA_ENABLE_SIGN_UP: ${ARTHVEDA_ENABLE_SIGN_UP}
            ARTHVEDA_ENABLE_SIGN_IN: ${ARTHVEDA_ENABLE_SIGN_IN}
            ARTHVEDA_ENABLE_GOOGLE_OAUTH: ${ARTHVEDA_ENABLE_GOOGLE_OAUTH}
            ARTHVEDA_GOOGLE_REDIRECT_URL: ${ARTHVEDA_GOOGLE_REDIRECT_URL}
            ARTHVEDA_GOOGLE_CLIENT_ID: ${ARTHVEDA_GOOGLE_CLIENT_ID}
            ARTHVEDA_GOOGLE_CLIENT_SECRET: ${ARTHVEDA_GOOGLE_CLIENT_SECRET}
            ARTHVEDA_API_CIPHER_KEY: ${ARTHVEDA_API_CIPHER_KEY}
            ARTHVEDA_PADDLE_API_KEY: ${ARTHVEDA_PADDLE_API_KEY}
            ARTHVEDA_PADDLE_WEBHOOK_SECRET: ${ARTHVEDA_PADDLE_WEBHOOK_SECRET}
            TZ: ${TZ}
        ports:
            - 1337:1337
        networks:
            - arthveda_network
            - caddy_net
        volumes:
            - ./volumes/api_logs:/app/logs
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy
                restart: true

    db:
        container_name: arthveda_db
        image: postgres:17.4-alpine
        environment:
            PGPORT: 42069
            POSTGRES_DB: ${ARTHVEDA_DB_NAME}
            POSTGRES_USER: ${ARTHVEDA_DB_USER}
            POSTGRES_PASSWORD: ${ARTHVEDA_DB_PASSWORD}
        ports:
            - 42069:42069
        networks:
            - arthveda_network
            - caddy_net
        volumes:
            - ./volumes/db_data:/var/lib/postgresql/data
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${ARTHVEDA_DB_USER} -d ${ARTHVEDA_DB_NAME}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
